version: '3.7'
services:
  metadata:
    restart: unless-stopped  
    environment:
        - POSTGRES_PASSWORD=postgres
    ports:
        - :5432
    image: postgres:11.6-alpine
    volumes:
      - arcion_pg:/var/lib/postgresql/data     
            
  loadgen:
    image: robertslee/sybench:${SYBENCH_TAG:-latest}
    restart: unless-stopped  
    environment:
      - ARCION_HOME=/arcion
      - MYSQL_ROOT_PASSWORD=password    
      - PG_ROOT_PASSWORD=password    
      - YCSB_PASSWORD=password    
      - SBT_PASSWORD=password
      - SRCDB_HOST=$COMPOSE_PROJECT_NAME-srcdb-1
      - DSTDB_HOST=$COMPOSE_PROJECT_NAME-dstdb-1
      - SCRIPT_DIR=/
    ports:
      - :7681
    volumes:
      - arcion_bin:/arcion 
      - ../../arcion-jobs:/jobs/
    depends_on:
      - metadata
      - srcdb
      - dstdb

  srcdb:
    image: mysql:${MYSQL_TAG:-latest}
    restart: unless-stopped  
    environment:
      - MYSQL_ROOT_PASSWORD=password    
    ports:
      - :3306
    volumes:
      - /var/lib/mysql

  dstdb:
    image: mysql:${MYSQL_TAG:-latest}
    restart: unless-stopped  
    environment:
      - MYSQL_ROOT_PASSWORD=password    
    ports:
      - :3306
    volumes:
      - /var/lib/mysql

networks:
  default:
    name: arcnet
    external: true

volumes:
  arcion_pg: {}
  arcion_bin:
    external: true
