# GUI test of MySQL to SingleStore 
name: cli-mysql-mysql
on:
  workflow_dispatch:
    branches: 
    inputs:
      ARCION_BIN_URL:
        description: 'Arcion binary URL'
        required: true
        default: 'https://arcion-releases.s3.us-west-1.amazonaws.com/general/replicant/replicant-cli-23.01.05.3.zip'
        type: string      
env:
  SINGLE_STORE_LIC: ${{ secrets.SINGLE_STORE_LIC }}    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: |
          pwd
          ls
      - name: arcion lic setup
        # NOTE: license cannot be passed in as a volume.  docker is running inside docker. the file in created inside docker not avail to compose
        run: |
          docker volume create arcion_lic
          docker run --rm -v arcion_lic:/config -e ARCION_LIC="${{ secrets.ARCION_LIC }}" alpine sh -c 'echo $ARCION_LIC | base64 -d > /config/replicant.lic'
          # DEBUG: docker run --rm -v arcion_lic:/config ubuntu cat /config/replicant.lic
      - name: arcion binary setup
        run: |
          docker volume create arcion_bin
          docker run --rm -v arcion_bin:/arcion -e ARCION_BIN_URL="${{ github.event.inputs.ARCION_BIN_URL }}" alpine sh -c 'cd /arcion; if [ ! -d replicant-cli ]; then wget -O arcion.zip $ARCION_BIN_URL; unzip arcion.zip; fi'  
          # DEBUG: docker run -it -v arcion_bin:/arcion alpine sh        
      - name: env
        run: |
          ps -aef
          

    
