# CLI 
name: cli
on:
  workflow_dispatch:
    branches: 
    inputs:
      ARCION_BIN_URL:
        description: 'Arcion binary URL'
        required: true
        default: 'https://arcion-releases.s3.us-west-1.amazonaws.com/general/replicant/replicant-cli-23.01.05.3.zip'
        type: string      
      COMPOSE_FILE:
        description: 'Docker Compose File'
        required: true
        default: 'compose/climymy/aclimymy.yaml'
        type: string 
env:
  SINGLE_STORE_LIC: ${{ secrets.SINGLE_STORE_LIC }}    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: |
          pwd
          ls
      - name: arcion binary setup
        run: |
          docker volume create arcion_bin
          docker run --rm -v arcion_bin:/arcion -e ARCION_BIN_URL="${{ github.event.inputs.ARCION_BIN_URL }}" alpine sh -c 'cd /arcion; if [ ! -d replicant-cli ]; then wget -O arcion.zip $ARCION_BIN_URL; unzip arcion.zip; fi'  
          docker run --rm -v arcion_bin:/arcion -e ARCION_LICENSE="${{ secrets.ARCION_LICENSE }}" alpine sh -c 'echo $ARCION_LICENSE | base64 -d > /arcion/replicant-cli/replicant.lic'
          # DEBUG: docker run -it -v arcion_bin:/arcion alpine sh        
      - name: Log of containers
        run: |
          echo ${{ github.event.inputs.COMPOSE_FILE }}
          docker compose -f ${{ github.event.inputs.COMPOSE_FILE }} up -d
      - name: DML on sysbench and ycsb
        run: |
          echo "here"
          #docker exec loadgen "/scripts/ycsb.sh"
          #docker exec loadgen "/scripts/sysbench.sh"
          

    
