name: Publish Docker image

# Change this to be on push action when it's working?
on: workflow_dispatch

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3 
        # Github recommends pinning this to a specific SHA rather than @v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2 
        # Github recommends pinning this to a specific SHA rather than @v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2 
        # Github recommends pinning this to a specific SHA rather than @v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push docker images
        uses: docker/build-push-action@v4
        # Github recommends pinning this to a specific SHA rather than @v4
        with:
          context: .
          file: load-generator/Dockerfile.arcdemo
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: | # Alternatively use ${{ secrets.DOCKER_USERNAME }} instead of robertslee and arcionlabs/arcion-loadgen instead of ${{ github.repository }}
            robertslee/arcdemo:latest
            ghcr.io/${{ github.repository }}:latest

      # - name: Build docker images
      #   run: |
      #     docker buildx create --name mybuilder
      #     docker buildx use mybuilder
      #     docker buildx inspect --bootstrap
      #     docker buildx build --push --platform=linux/amd64,linux/arm64/v8 -t robertslee/arcdemo -f load-generator/Dockerfile.arcdemo .
      
      # - name: Push images to Docker Hub
      #   run: |
      #     docker tag 597de83199f4 robertslee/arcdemo
      #     docker push robertslee/arcdemo

      # - name: Push images to GHCR
      #   run: | # Is first line needed?
      #     docker images | grep arcdemo
      #     docker tag a1985aa6af86 ghcr.io/arcionlabs/arcdemo
      #     docker push ghcr.io/arcionlabs/arcdemo:latest