# GUI test of MySQL to SingleStore 
name: gui-mysql-singlestore
on:
  workflow_dispatch:
    branches: 
env:
  SINGLE_STORE_LIC: ${{ secrets.SINGLE_STORE_LIC }}    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: |
          pwd
          ls
      - name: arcion lic setup
        run: |
          mkdir arcion_lic
          echo ${{ secrets.ARCION_LIC }} | base64 --decode > arcion_lic/replicant.lic
          ARCION_LIC_DIR=`pwd`/arcion_lic
          echo "ARCION_LIC_DIR=$(echo $ARCION_LIC_DIR)" >> $GITHUB_ENV
      - name: Build the stack
        run: docker compose -f arcion-mysql-s2-compose.yaml up -d
      - name: Wait for Running Status
        run: |
          x=1
          while [ $x -le 5 ]
          do
            docker compose ls
            docker compose -f arcion-mysql-s2-compose.yaml ps
            sleep 10
            x=$(( $x + 1 ))
          done
      - name: Log of containers
        run: |
          docker compose -f arcion-mysql-s2-compose.yaml logs
      - name: DML on sysbench and ycsb
        run: |
          docker exec loadgen "/scripts/ycsb.sh"
          docker exec loadgen "/scripts/sysbench.sh"
    
