# GUI test of MySQL to SingleStore 
name: gui-mysql-singlestore
on:
  workflow_dispatch:
    branches: 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: |
          pwd
          ls
      - name: arcion lic setup
        run: |
          mkdir arcion_lic
          echo $ARCION_LIC | base64 --decode > arcion_lic/replicant.lic
          ARCION_LIC_DIR=`pwd`/arcion_lic/replicant.lic
          echo "ARCION_LIC_DIR=$(echo $ARCION_LIC_DIR)" >> $GITHUB_ENV
      - name: Build the stack
        run:  docker compose -f arcion-mysql-s2-compose.yaml up -d
    
